### ISSUE TITLE
Azure File Copy stopped working after last system updates on the VM

### ISSUE THREAD

**Issue by dac-scherevko** [Microsoft/vso-agent-tasks#1008]
We have 
•	The following VMs in East US 2: crspvmdev and crspvmbeta (Windows Server 2012 R2 Datacenter);
•	Release definitions with the Azure Copy File step, that targets the resource group with the servers,

The release had been working fine until last week, but today we had to restart our VMs because, once we connected to them via remote desktop, the servers show a warning to restart them. 
After the restart the release give us the error:
1.	2015-12-22T19:54:05.5516248Z Copy started for machine: 'crspvmdev'
2.	2015-12-22T19:58:12.5669685Z ##[debug]fqdn = crspvmdev.cloudapp.net
3.	2015-12-22T19:58:12.5679915Z ##[debug]storageAccount = crspdiagnosticdev
4.	2015-12-22T19:58:12.5679915Z ##[debug]containerName = 3f359e7c-b68c-4eca-8a20-df592e95e420
5.	2015-12-22T19:58:12.5689896Z ##[debug]sasToken = ?sv=2015-02-21&sr=c&sig=F6m92JGDiUOrDVPctaXINM3JMDfxWROiYHDxGmect9E%3D&se=2015-12-22T21%3A54%3A05Z&sp=rwdl
6.	2015-12-22T19:58:12.5689896Z ##[debug]azCopyLocation = C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\agents\default\Agent\Worker\Tools\AzCopy
7.	2015-12-22T19:58:12.5689896Z ##[debug]targetPath = C:\CRSP\CrspCostTranformation_vso
8.	2015-12-22T19:58:12.5699881Z ##[debug]cleanTargetBeforeCopy = false
9.	2015-12-22T19:58:12.5699881Z ##[debug]winRMPort = 5986
10.	2015-12-22T19:58:12.5713498Z ##[debug]httpProtocolOption = 
11.	2015-12-22T19:58:12.5723330Z ##[debug]skipCACheckOption = -SkipCACheck
12.	2015-12-22T19:58:12.5723330Z ##[debug]enableDetailedLogging = false
13.	2015-12-22T19:58:12.5729907Z ##[debug]additionalArguments = 
14.	2015-12-22T19:58:12.5729907Z ##[debug]Loading .NET assembly: Microsoft.IdentityModel.Clients.ActiveDirectory.dll
15.	2015-12-22T19:58:12.5739896Z ##[debug]Loading .NET assembly: Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms.dll
16.	2015-12-22T19:58:12.5739896Z ##[debug]Loading .NET assembly: Microsoft.TeamFoundation.Build.VsTestLogger.dll
17.	2015-12-22T19:58:12.5749887Z ##[debug]Loading .NET assembly: Microsoft.TeamFoundation.Client.dll
18.	2015-12-22T19:58:12.5749887Z ##[debug]Loading .NET assembly: Microsoft.TeamFoundation.Common.dll
19.	2015-12-22T19:58:12.5749887Z ##[debug]Loading .NET assembly: Microsoft.TeamFoundation.DistributedTask.Agent.Common.dll
20.	2015-12-22T19:58:12.5759880Z ##[debug]Loading .NET assembly: Microsoft.TeamFoundation.DistributedTask.Agent.Interfaces.dll
21.	2015-12-22T19:58:12.5759880Z ##[debug]Loading .NET assembly: Microsoft.TeamFoundation.DistributedTask.Agent.Logger.dll
22.	2015-12-22T19:58:12.5769879Z ##[debug]Loading .NET assembly: Microsoft.TeamFoundation.DistributedTask.Agent.Strings.dll
23.	2015-12-22T19:58:12.5769879Z ##[debug]Loading .NET assembly: Microsoft.TeamFoundation.DistributedTask.Agent.Worker.Common.dll
24.	2015-12-22T19:58:12.5779894Z ##[debug]Loading .NET assembly: Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll
25.	2015-12-22T19:58:12.5779894Z ##[debug]Loading .NET assembly: Microsoft.TeamFoundation.DistributedTask.WebApi.dll
26.	2015-12-22T19:58:12.5779894Z ##[debug]Loading .NET assembly: Microsoft.TeamFoundation.DistributedTask.Worker.dll
27.	2015-12-22T19:58:12.5789883Z ##[debug]Loading .NET assembly: Microsoft.TeamFoundation.VersionControl.Client.dll
28.	2015-12-22T19:58:12.5799911Z ##[debug]Loading .NET assembly: Microsoft.TeamFoundation.VersionControl.Common.dll
29.	2015-12-22T19:58:12.5799911Z ##[debug]Loading .NET assembly: Microsoft.VisualStudio.Services.Client.dll
30.	2015-12-22T19:58:12.5809889Z ##[debug]Loading .NET assembly: Microsoft.VisualStudio.Services.Common.dll
31.	2015-12-22T19:58:12.5809889Z ##[debug]Loading .NET assembly: Microsoft.VisualStudio.Services.WebApi.dll
32.	2015-12-22T19:58:12.5809889Z ##[debug]Loading .NET assembly: Newtonsoft.Json.dll
33.	2015-12-22T19:58:12.5819881Z ##[debug]Loading .NET assembly: System.Net.Http.Formatting.dll
34.	2015-12-22T19:58:12.5819881Z ##[debug]Loading .NET assembly: Microsoft.TeamFoundation.DistributedTask.Task.DevTestLabs.dll
35.	2015-12-22T19:58:12.5829874Z ##[debug]Loading .NET assembly: Microsoft.VisualStudio.Services.DevTestLabs.Client.dll
36.	2015-12-22T19:58:12.5829874Z ##[debug]Loading .NET assembly: Microsoft.VisualStudio.Services.DevTestLabs.Common.dll
37.	2015-12-22T19:58:12.5829874Z ##[debug]Loading .NET assembly: Microsoft.VisualStudio.Services.DevTestLabs.Definition.dll
38.	2015-12-22T19:58:12.5839885Z ##[debug]Loading .NET assembly: Microsoft.VisualStudio.Services.DevTestLabs.Deployment.dll
39.	2015-12-22T19:58:12.5839885Z ##[debug]Initiating copy on crspvmdev.cloudapp.net 
40.	2015-12-22T19:58:12.6250649Z ##[debug]Finished AzureFileCopy operation on crspvmdev
41.	2015-12-22T19:58:12.6280628Z ##[debug]Deployment logs for AzureFileCopy operation on crspvmdev 
42.	2015-12-22T19:58:12.6417339Z ##[debug]Failed to establish remote power shell session to the deployment machine crspvmdev.cloudapp.net on the port:5986 due to unexpected exception. Error Message:
43.	2015-12-22T19:58:12.6417339Z System.Management.Automation.Remoting.PSRemotingTransportException: Connecting to remote server crspvmdev.cloudapp.net failed with the following error message : WinRM cannot complete the operation. Verify that the specified computer name is valid, that the computer is accessible over the network, and that a firewall exception for the WinRM service is enabled and allows access from this computer. By default, the WinRM firewall exception for public profiles limits access to remote computers within the same local subnet. For more information, see the about_Remote_Troubleshooting Help topic.
44.	2015-12-22T19:58:12.6427341Z    at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
45.	2015-12-22T19:58:12.6427341Z    at System.Management.Automation.RemoteRunspace.Open()
46.	2015-12-22T19:58:12.6437336Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.PowershellExecutor.GetOpenedRunspace() in F:\v2.0\A2\_work\2\s\DevTestLabs\Client\Deployment\Deployment\PowershellExecutor.cs:line 413
47.	2015-12-22T19:58:12.6437336Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.PowershellExecutor.EstablishRemoteSession() in F:\v2.0\A2\_work\2\s\DevTestLabs\Client\Deployment\Deployment\PowershellExecutor.cs:line 330System.Management.Automation.Remoting.PSRemotingTransportException: Connecting to remote server crspvmdev.cloudapp.net failed with the following error message : WinRM cannot complete the operation. Verify that the specified computer name is valid, that the computer is accessible over the network, and that a firewall exception for the WinRM service is enabled and allows access from this computer. By default, the WinRM firewall exception for public profiles limits access to remote computers within the same local subnet. For more information, see the about_Remote_Troubleshooting Help topic.
48.	2015-12-22T19:58:12.6437336Z    at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
49.	2015-12-22T19:58:12.6447348Z    at System.Management.Automation.RemoteRunspace.Open()
50.	2015-12-22T19:58:12.6447348Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.PowershellExecutor.GetOpenedRunspace() in F:\v2.0\A2\_work\2\s\DevTestLabs\Client\Deployment\Deployment\PowershellExecutor.cs:line 413
51.	2015-12-22T19:58:12.6447348Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.PowershellExecutor.EstablishRemoteSession() in F:\v2.0\A2\_work\2\s\DevTestLabs\Client\Deployment\Deployment\PowershellExecutor.cs:line 364
52.	2015-12-22T19:58:12.6457329Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.RetryExecutor.Execute(Action action) in F:\v2.0\A2\_work\2\s\DevTestLabs\Client\Deployment\RetryExecutor.cs:line 86
53.	2015-12-22T19:58:12.6457329Z    at System.Threading.Tasks.Task.Execute()
54.	2015-12-22T19:58:12.6457329Z --- End of stack trace from previous location where exception was thrown ---
55.	2015-12-22T19:58:12.6467331Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
56.	2015-12-22T19:58:12.6467331Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
57.	2015-12-22T19:58:12.6467331Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.PowershellExecutor.<Initialize>d__29.MoveNext() in F:\v2.0\A2\_work\2\s\DevTestLabs\Client\Deployment\Deployment\PowershellExecutor.cs:line 215
58.	2015-12-22T19:58:12.6477340Z --- End of stack trace from previous location where exception was thrown ---
59.	2015-12-22T19:58:12.6477340Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
60.	2015-12-22T19:58:12.6477340Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
61.	2015-12-22T19:58:12.6487355Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.PowershellExecutor.<Initialize>d__23.MoveNext() in F:\v2.0\A2\_work\2\s\DevTestLabs\Client\Deployment\Deployment\PowershellExecutor.cs:line 107
62.	2015-12-22T19:58:12.6487355Z --- End of stack trace from previous location where exception was thrown ---
63.	2015-12-22T19:58:12.6487355Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
64.	2015-12-22T19:58:12.6497341Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
65.	2015-12-22T19:58:12.6497341Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.RemoteDeploymentHelper.<Initialize>d__0.MoveNext() in F:\v2.0\A2\_work\2\s\DevTestLabs\Client\Deployment\Deployment\RemoteDeploymentHelper.cs:line 37
66.	2015-12-22T19:58:12.6507355Z --- End of stack trace from previous location where exception was thrown ---
67.	2015-12-22T19:58:12.6507355Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
68.	2015-12-22T19:58:12.6507355Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
69.	2015-12-22T19:58:12.6517329Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.DeploymentClient.<RunAsync>d__24.MoveNext() in F:\v2.0\A2\_work\2\s\DevTestLabs\Client\Deployment\Deployment\DeploymentClient.cs:line 316
70.	2015-12-22T19:58:12.6577340Z Copy status for machine 'crspvmdev' : 'Failed'
71.	2015-12-22T19:58:12.6647358Z Copy failed on machine 'crspvmdev' with following message : 'Connecting to remote server crspvmdev.cloudapp.net failed with the following error message : WinRM cannot complete the operation. Verify that the specified computer name is valid, that the computer is accessible over the network, and that a firewall exception for the WinRM service is enabled and allows access from this computer. By default, the WinRM firewall exception for public profiles limits access to remote computers within the same local subnet. For more information, see the about_Remote_Troubleshooting Help topic.'
72.	2015-12-22T19:58:12.7363347Z ##[debug]System.Management.Automation.RuntimeException: Copy to one or more machines failed. For more info please refer to http://aka.ms/azurefilecopyreadme
73.	2015-12-22T19:58:12.7425893Z ##[debug][Azure Call]Deleting container: 3f359e7c-b68c-4eca-8a20-df592e95e420 in storage account: crspdiagnosticdev
74.	2015-12-22T19:58:12.9300182Z ##[debug][Azure Call]Deleted container: 3f359e7c-b68c-4eca-8a20-df592e95e420 in storage account: crspdiagnosticdev
75.	2015-12-22T19:58:12.9310425Z ##[debug]Completed Azure File Copy Task for Azure VMs Destination
76.	2015-12-22T19:58:12.9350188Z ##[error]Copy to one or more machines failed. For more info please refer to http://aka.ms/azurefilecopyreadme

Since we have not change anything in the releases setup, I guess something has happened elsewhere, most probably on the VMs after the latest updates on the Windows Server 2012 R2 Datacenter servers:

BTW, other  release definitions for Azure cloud services or for web-sites still work fine.

Please help

**Comment by pryenugu** [comment]
Can you run this command In a Powershell window on the affected VM's and check the status of the winrm HTTPS listener? 

winrm e winrm/config/listener

This should show if the https listener is configured properly.

**Comment by dac-scherevko** [comment]
Praneeth, thanks for such prompt reply!

Yes it looks the listener is configured and up:
[cid:image002.jpg@01D13CD5.A477CBB0]
I ran the powershell command and made the snapshot on the crspvmdev VM






Sergiy Cherevko

Senior Programmer Analyst

DAC Group / Canada



416.492.3214 ext. 6295

**Comment by pryenugu** [comment]
Okay can you verify these two:

1. The public port of the VM is 5986 in the azure portal. 
2. The update could have reset some firewall rules. You would need to make sure that the inbound rule for 5986 is open in Windows firewall.

**Comment by dac-scherevko** [comment]
1.  ?Yes, there is the setting in Azure portal for the VM: Powershell Endpoint -> TCP protocol -> public port 5986
  2.  Yes, there is the inbound rule for public and private networks for Windows Remote Management in Firewall rules on the VM; plus I added another similar rule for the 5986 port explicitly.

Thanks,
Sergiy Cherevko



________________________________

**Comment by pryenugu** [comment]
Can you run these set of PowerShell  commands from some machine just to check whether WinRM is up and configured properly on the machines you specified :

```PowerShell
$soptions = New-PSSessionOption -SkipCACheck
$cred = Get-Credential
$computername = 'anuvm0.westus.cloudapp.azure.com'
$computerport = '5986'
Enter-PSSession -ComputerName $computername -Port $computerport -Credential $cred -SessionOption $soptions -UseSSL
```

**Comment by pryenugu** [comment]
Post discussion with @dac-scherevko , The Azure VM had some ACL lists specified for the PowerShell endpoint which were restricting access to only certain IP addresses in which the build agents IP address did not fall into. So clearing the access control list for the remote PowerShell endpoint helped solve this issue.

**Comment by dac-scherevko** [comment]
Thanks for your guides and help!

**Comment by br3xion** [comment]
Hi @pryenugu,
I would like to know how can i Clear the access control list for the remote Powershell? I mean... Where can i find that list?

**Comment by dac-scherevko** [comment]
I did this in the Azure portal for my VM, and there in ACL for the WinRM/PowerShell endpoint:

![acl](https://cloud.githubusercontent.com/assets/14787723/12146781/899219b2-b463-11e5-8bd4-13424e332c61.jpg)

**Comment by br3xion** [comment]
Did you find that in the old azure portal?
I've created an Azure VM using the new azure portal.
So i guess its kinda different in that case, I cant find that list anywhere in the new azure portal.

**Comment by dac-scherevko** [comment]
yes, the old portal. But the new portal shows the same configurations. 
However since I created the VM in the old portal, it shows under a Virtual machines (classic) in the new portal:
![vms](https://cloud.githubusercontent.com/assets/14787723/12147302/3b117c62-b466-11e5-891c-fc3e990deeea.jpg)

**Comment by br3xion** [comment]
Yeah. I know that there is a difference between both VM (created in the Clasic portal and new Portal)
I cant find that list in a VM Azure created in the new portal.

Anyways. I found that list in a VM azure creates using the old portal.
Do i clear the list ACL using in the powershell endpoint? Cause Its cleared already
![image](https://cloud.githubusercontent.com/assets/14997977/12147799/c199661c-b468-11e5-8215-eff723916d92.png)

**Comment by dac-scherevko** [comment]
Basically, I removed ALL entries from the ACL list. This way ALL traffic is permitted. This may lead to security concerns, in my case it is ok

**Comment by br3xion** [comment]
I did the following:
Create a new Azure VM (New portal)
Then i defined my Release:

![image](https://cloud.githubusercontent.com/assets/14997977/12149944/970d21f2-b474-11e5-96f6-d3d2dd23aafa.png)


and Still getting the following error:

Connecting to remote server ##AzureVM IP## failed with the following error message : WinRM cannot complete the operation. Verify that the specified computer name is valid, that the computer is accessible over the network, and that a firewall exception for the WinRM service is enabled and allows access from this computer. By default, the WinRM firewall exception for public profiles limits access to remote computers within the same local subnet. For more information, see the about_Remote_Troubleshooting Help topic. For more info please refer to http://aka.ms/azurefilecopyreadme

Need assistance :(  i 've been following all the steps from microsoft documentation

**Comment by pavanadepu2** [comment]
Simply download the below files onto the target azure VM into some folder:

       https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/201-vm-winrm-windows/ConfigureWinRM.ps1
	https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/201-vm-winrm-windows/makecert.exe
	https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/201-vm-winrm-windows/winrmconf.cmd


Then, Run the below command which configures a winrm https listener for target VM using a self-signed certificate:
	.\ConfigureWinRM.ps1 *.westus.cloudapp.azure.com
	
	Note: 1. Replace the westus in the above command with the location of VM.
		  2. Add a inbound NAT rule for target port 5986, if the VM is backed up by a Security Group or LoadBalancer.

**Comment by br3xion** [comment]
Jesus christ... 
Thanks a Lot @pavanadepu2 .
Srsly GitHub.. What a nice place where i can find many answer..

**Comment by pavanadepu2** [comment]
We have published these scripts along with couple of csm templaltes to provide smoother experience for our users. Please feel free to contact us for any Azure Tasks related issues.

**Comment by anabhijeet** [comment]
I am still getting following error, after doing all possible steps
`##[error]Storage account: aqmlocalstore not found. Selected Connection 'ServicePrincipal' supports storage account of Azure Resource Manager type only.`
 
My AzureVMs File Copy task still failing.

**Comment by fijiancoder** [comment]
Thanks @pavanadepu1 
I salute you. Was stuck on this for days. Finally got it to work.

**Comment by ajklotz** [comment]
For anyone that has been going down this path and still runing into issues, don't forget the possibility of being blocked by corporate firewall. I went through all the steps listed here and in Muthu's blog and finally got the bright idea of asking our NoC team if the port was blocked. It was - and now I'm getting successful Azure File Copy tasks.
