### ISSUE TITLE
Unexpected exit code 1 returned from tool gulp.cmd

### ISSUE THREAD

**Issue by Dodelkin** [Microsoft/vso-agent-tasks#250]
Hello.
I want to compile gulpfile through vso, but I have a problem during the build. I poprobyval gulpfile to replace your file from https://github.com/Microsoft/vso-agent-samples/tree/2ff3120af8428016be900202693ad66531a15079/gulp, just updating package.json
I checked, and the way to set up folders and gulpfile, but it did not help, all the same mistake. And I do not know the cause, because the log does nothing.
Sorry for bad english)
The contents of the log:
2015-06-11T21:14:03.4313879Z Executing the powershell script: C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\tasks\Gulp\0.5.2\Gulptask.ps1
2015-06-11T21:14:03.6313859Z C:\NPM\Modules\gulp.cmd --gulpfile C:\a\51f50c38\Business Tools\gulpfile.js 
2015-06-11T21:14:04.0393867Z [21:14:04] 
2015-06-11T21:14:04.8543013Z ##[error]Unexpected exit code 1 returned from tool gulp.cmd

![help](https://cloud.githubusercontent.com/assets/8626534/8118646/ef3092e0-1098-11e5-822b-d6b1d6e497bf.png)

**Comment by bryanmacfarlane** [comment]
What happens when you run that gulpfile.js from a developers machine?
Does it help if you go in advanced and set the working directory?

**Comment by Dodelkin** [comment]
When I run gulpfile at home, it works, here's a screenshot of the Task Runner
I tried to point out different ways to gulpfile, in the folder with the solution, and where lies .sln file, but all my attempts, one mistake.
![test](https://cloud.githubusercontent.com/assets/8626534/8118967/dd5f2ef8-109a-11e5-9680-c8c5ba109d8d.png)
![help_2](https://cloud.githubusercontent.com/assets/8626534/8118966/dd5e7198-109a-11e5-9d38-19b7d4f1a4eb.png)
![help_1](https://cloud.githubusercontent.com/assets/8626534/8118965/dd5e7544-109a-11e5-8d95-ae7be6832314.png)

**Comment by sdaly2107** [comment]
I have the same problem here...  tried setting the working path explicitly too with no joy...

**Comment by bryanmacfarlane** [comment]
My theory is there's a space in the path and the powershell isn't quoting it.  I'll have someone look into it today

**Comment by sergei-startsev** [comment]
I came across the same issue and the cause was a path with space. I have changed a name of a repository and it works properly.

**Comment by bryanmacfarlane** [comment]
Yeah, we fixed it today.  Should be in the service on the next update in a couple of weeks

**Comment by sdaly2107** [comment]
Nice one, thank you :)

**Comment by qwert789** [comment]
Hi,  i still have issue with tfs online agent gives: 
Unexpected exit code 1 returned from tool gulp.cmd
There is no spaces in path and i also tried to set working directory:
![localtaskrunner](https://cloud.githubusercontent.com/assets/1618071/10410869/a14f06c8-6f58-11e5-82a2-be59f13e9259.JPG)
![visualstudioonline](https://cloud.githubusercontent.com/assets/1618071/10410868/a14f0362-6f58-11e5-8cc7-d5b9a012d60d.JPG)
